keys:
  - &users
    - &ta age1qul0y992gp00x2xjus47c6rxax93ve2p6kv7llan3ku7qac3js6sj2wrpn
  - &hosts
    - &dell age15954qfmg0vfp4vg6vhavv88svtlwhecpxf24r9aduhgx9lg35c3q4x0kx7
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *ta
      - *dell