{
  config,
  pkgs,
  host,
  inputs,
  username,
  options,
  ...
}: {
  imports = [
    ./alacritty.nix
    ./atuin.nix
    ./btop.nix
    ./cava.nix
    #./chromium.nix
    #./conky.nix
    ./direnv.nix
    ./eza.nix
    ./firefox.nix
    ./fzf.nix
    ./git.nix
    ./gnome-extensions.nix
    ./gnome.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./idleinhibitor.nix
    ./kitty.nix
    #./libnotify.nix
    ./mangohud.nix
    ./man.nix
    ./nix-index.nix
    ./packages.nix
    #./plasma.nix
    ./spicetify.nix
    #./starship.nix
    ./stylix.nix
    #./vscode.nix
    ./wezterm.nix
    #./xfce/xfce.nix
    ./zsh.nix

    #./sops.nix
  ];
}
