---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/Docker/Docker/Qbittorrent_Config:/config
      - /mnt/Docker/Downloads:/downloads
      - /mnt/Raid/Downloads:/downloads1
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 9696:9696
    volumes:
      - /mnt/Docker/Docker/Prowlarr_Config:/config
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true
      - TZ=Asia/Kolkata
    ports:
      - 9117:9117
    volumes:
      - /mnt/Docker/Docker/Jackett_Config:/config
      - /mnt/Docker/Downloads:/downloads
      - /mnt/Raid/Downloads:/downloads1
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/Docker/Docker/JellyFin_Docker:/config
      - /mnt/Raid/Learn/Bonus:/data
      - /mnt/E_Disk/Learn/Bonus:/data1
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/Docker/Docker/Sonarr_Config:/config
      - /mnt/Raid/Learn/Bonus:/data
      - /mnt/Docker/Downloads:/downloads
      - /mnt/Raid/Downloads:/downloads1
      - /mnt/E_Disk/Learn/Bonus:/data1
    ports:
      - 8989:8989
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    user: 1000:1000
    ports:
      - 700:8080
    volumes:
      - /:/data
      - /mnt/Docker/Docker/FileBrowser_Config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2800:8080
    environment:
      - TZ=Asia/Kolkata
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://6967316132:AAH8IclO_3btJ9ovRpD2CRBoKwlJZ53ywhQ@telegram/?channels=-4105555598
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_TOKEN=/run/secrets/access_token
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/Docker/Docker/Radarr_Config:/config
      - /mnt/Raid/Learn/Bonus:/data
      - /mnt/Docker/Downloads:/downloads
      - /mnt/Raid/Downloads:/downloads1
      - /mnt/E_Disk/Learn/Bonus:/data1
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/Docker/Docker/Bazarr_Docker:/config
      - /mnt/Raid/Learn/Bonus:/data
      - /mnt/E_Disk/Learn/Bonus:/data1
    ports:
      - 6767:6767
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 2500:3000
    volumes:
      - /mnt/Docker/Docker/HomePage_Config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/Raid:/mnt/Raid
      - /mnt/test:/mnt/SSD
      - /mnt/E_Disk:/mnt/E_Disk
    restart: unless-stopped

#  readarr:
#    image: lscr.io/linuxserver/readarr:develop
#    container_name: readarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Asia/Kolkata
#    volumes:
#      - /mnt/Docker/Docker/Readarr_Config:/config
#      - /mnt/Raid/Learn/Bonus/Books:/books
#      - /mnt/Docker/Downloads:/downloads
#      - /mnt/Raid/Downloads:/downloads1
#      - /mnt/E_Disk/Learn/Bonus:/data
#    ports:
#      - 8787:8787
#    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
         - LOG_LEVEL=debug
         - TZ=Asia/Kolkata
    ports:
         - 5055:5055
    volumes:
         - /mnt/Docker/Docker/Jellyseer_Config:/app/config
    restart: unless-stopped

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /mnt/Docker/Docker/Duplicati_Config:/config
      - /mnt/Raid/Backup/:/backups
      - /mnt/Docker/:/source
      - /home/rishabh/:/source_home
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: tailscaler
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - TS_USERSPACE=true
      - TS_AUTH_KEY=tskey-auth-kng2WdZnwp11CNTRL-kkX3gp8MSqDCnRAxjM3ZqDLTJ8nFK83L
      - TS_ROUTES=192.168.1.0/24
      - TS_EXTRA_ARGS=--accept-routes
      - TS_EXTRA_ARGS=--accept-risk=all
    volumes:
      - /data:/var/lib
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: unless-stopped

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - APP_TIMEZONE=Asia/Kolkata
      - DISPLAY_TIMEZONE=Asia/Kolkata
      - SPEEDTEST_SCHEDULE=*/30 * * * *
      - DB_CONNECTION=sqlite
      - TELEGRAM_BOT_TOKEN=6260786279:AAFBHq8WQgOB8kux1Fnfvwc8z9bfndDj6c4
      - APP_KEY=base64:ov/pvp6VKvBWL3XfT5N+6yg11UNzUchr9LCvMF/G/AE=
    volumes:
      - /mnt/Docker/Docker/Speedtest-Tracker_Config:/config
    ports:
      - 8443:80
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VERSION=docker
      - PLEX_CLAIM= claim-GnJWXtejYAuEC4mbsQxK
#    ports:
#      - "32400:32400"
#      - "1900:1900/udp"
#      - "8324:8324"
#      - "32410:32410/udp"
#      - "32412:32412/udp"
#      - "32413:32413/udp"
#      - "32414:32414/udp"
#      - "32469:32469"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/Docker/Docker/Plex_Config:/config
      - /mnt/Raid/Learn/Bonus:/data
      - /mnt/E_Disk/Learn/Bonus:/data1
    restart: unless-stopped

#  adguardhome:
#    container_name: adguardhome
#    restart: unless-stopped
#    network_mode: host
#    volumes:
#      - '/mnt/Docker/Docker/Adguard_Config/work:/opt/adguardhome/work'
#      - '/mnt/Docker/Docker/Adguard_Config/conf:/conf'
#    image: adguard/adguardhome

#  adguardhome:
#    image: adguard/adguardhome
#    container_name: adguardhome
#    network_mode: host
#    volumes:
#      - /mnt/Docker/Docker/Adguard_Config/conf:/opt/adguardhome/conf
#      - /mnt/Docker/Docker/Adguard_Config/work:/opt/adguardhome/work
#    ports:
        # DNS
#      - 53:53
          # # DHCP server
          # - 67:67/udp
          # - 68:68/udp
          # # HTTPS/DNS-over-HTTPS
          # - 443:443/tcp
          # # DNS-over-TLS
          # - 853:853/tcp
          # # DNS-over-QUIC
         # - 853:853/udp
          # # DNSCrypt
          # - 5443:5443/tcp
          # - 5443:5443/udp
          # # WebUI
#      - 3000:3000/tcp
#    restart: unless-stopped

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  watchstate:
    image: ghcr.io/arabcoders/watchstate:latest
#    network_mode: host
    user: "0:0"
    container_name: watchstate
    ports:
        - 8500:8080
        - 8600:9000
    restart: unless-stopped
    volumes:
      - /mnt/Docker/Docker/Watchstate_Config:/config:rw # mount current directory to container /config directory.

#  syncthing:
#      image: lscr.io/linuxserver/syncthing:latest
#      container_name: syncthing
#      hostname: dell #optional
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Asia/Kolkata
#      volumes:
#        - /mnt/Docker/Docker/Syncthing_Config:/config
#        - /mnt:/data1
#        - /home/rishabh:/data2
#      ports:
#        - 8384:8384
#        - 22000:22000/tcp
#        - 22000:22000/udp
#        - 21027:21027/udp
#      restart: unless-stopped

#  lidarr:
#    image: lscr.io/linuxserver/lidarr:latest
#    container_name: lidarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Asia/Kolkata
#    volumes:
#      - /mnt/Docker/Docker/Lidarr_Config:/config
#      - /mnt/Raid/Learn/Bonus:/data
#      - /mnt/E_Disk/Learn/Bonus:/data1 #optional
#      - /mnt/Docker/Downloads:/downloads
#      - /mnt/Raid/Downloads:/downloads1
#    ports:
#      - 8686:8686
#    restart: unless-stopped
