name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create and switch to new branch
        run: |
          git checkout -b update-flake-lock-${{ github.run_id }}
      - name: Commit changes
        run: |
          git add flake.lock
          git commit -m "Update flake.lock"
      - name: Push changes
        run: |
          git push origin update-flake-lock-${{ github.run_id }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update flake.lock"
          body: "This PR updates the flake.lock file."
          branch: update-flake-lock-${{ github.run_id }}
          base: main
          labels: |
            dependencies
            automated